# Setup
title:               Lucas Flanagan
tagline:             'Student and Cybersecurity enthusiast.'
description:         'A minimalist portfolio showcasing cybersecurity write-ups and software projects.'
url:                 http://lucas-flanagan.github.io
absolute-url:        http://lucas-flanagan.github.io/
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lucas Flangan
  url:               https://www.linkedin.com/in/lucasflanagan01
  email:             lucasflanagan.is@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
